#%RAML 1.0 Trait
queryParameters:
  cdVal:
    required: true
    type: string
  incomeRowSrNo:
    required: false
    type: number
  custNo:
    required: false
    type: number
  fileNo:
    required: false
    type: number    